### ISSUE TITLE
Handle Bar Update

### ISSUE THREAD

**Issue by naffets77** [highslide-software/draggable-points#28]
Handle bars are great, but with the update the entire column no longer is draggable. Is it possible to provide an option to allow then entire column still be draggable?

As an aside, you also should probably update the plugin to use a 'handleCursor" option, as the 'cursor' option applies to the entire column. Since only the handlebar is now draggable having the ns-resize cursor show up when hovering over the rest of the column isn't great when considering usability.

**Comment by naffets77** [comment]
Playing with the code more I realized that you're automatically adding the ns-resize property to the handle bar, so removing the cursor option from the series solves that concern.

**Comment by highslide-software** [comment]
> Is it possible to provide an option to allow then entire column still be draggable?

There's no option for that currently, but you can override the method `useDragHandle` to always return `false`: 

```js
Highcharts.seriesTypes.column.prototype.useDragHandle = function () {
    return false;
}
```
[View live demo](http://jsfiddle.net/highcharts/AyUbx/2465/).

**Comment by naffets77** [comment]
Perfect, thanks.
