### ISSUE TITLE
Need previous version of draggable-points.js

### ISSUE THREAD

**Issue by simonoldridge** [highslide-software/draggable-points#31]
Hi there
My campaign website uses draggable points with Highcharts and I have some very involved javascript controlling one of the graphs.  The new version of draggable-points.js updated in May 2015 has caused (or maybe exposed...) lots of bugs in my code.  It would be hugely helpful if anyone could let me have a copy of the previous version of draggable-points.js please.  The relevant page on my site (which now is pretty buggy) is:  http://inequalitywatch.org/wealth-inequality/

I realise I'll have to update my code to work with the new version of draggable-points.js, but this is going to take me some time, and in the meantime, I'd like to run off the earlier version until I can sort it out (and I've got some people I've been trying to get involved in my project looking at the site tomorrow.... aaaaghhhh!).  I've been trying to reach Torstein Hønsi who developed draggable points but can't find his contact details.
many thanks :)

**Comment by simonoldridge** [comment]
Found the previous version.  Panic over.  Found it here if anyone wants it - http://go.jetswap.com/i/

**Comment by highslide-software** [comment]
The full history of the JavaScript file is available at https://github.com/highslide-software/draggable-points/commits/master/draggable-points.js

**Comment by simonoldridge** [comment]
Brilliant - many thanks :)

Love the software. 


Simon Oldridge
07889 379910
