### ISSUE TITLE
Column not redrawing after drag (Tested Chrome, IE11)

### ISSUE THREAD

**Issue by smcmurrin-RA** [highslide-software/draggable-points#32]
Main Demo: http://jsfiddle.net/highcharts/AyUbx/

Drag a handlebar, the handlebar stay's but the column it's associated with is not redrawn. Inspecting the code shows that it's an issue with "visibility:hidden" not being removed.

**Comment by highslide-software** [comment]
It's a bug in Highcharts, it's logged and fixed at https://github.com/highslide-software/highcharts.com/issues/4284
