### ISSUE TITLE
does not work with Highcharts.StockChart

### ISSUE THREAD

**Issue by sparc** [highslide-software/draggable-points#33]
would be great thtat it could work with Highcharts.StockChart's

**Comment by sebastianbochan** [comment]
http://jsfiddle.net/AyUbx/2561/ seems to working fine, could you supply unworking demo?

**Comment by sparc** [comment]
Hi

http://jsfiddle.net/agmo3bh2/

but i think the problem is due to using json.decode , not by the plugin 
itself

> http://jsfiddle.net/AyUbx/2561/ seems to working fine, could you supply
> unworking demo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/highslide-software/draggable-points/issues/33#issuecomment-116663973>.
>

-- 
Thanx & best regards ...

----------------------------------------------------------------
    David Saez
    On-Line Services 2000 S.L.
    http://www.ols.es
----------------------------------------------------------------

**Comment by highslide-software** [comment]
You need to disable data grouping and enable dragging: http://jsfiddle.net/highcharts/agmo3bh2/5/

**Comment by fabien-colpaert** [comment]
Hello,
I'm having trouble getting dragging option working on the hightstock. I npm installed latest version of highcharts and highcharts-draggable-points.
I have the Highcharts. Chart('container', {chart: {renderTo: 'container}} etc... 
plotOptions:{
series:{
point:{
events:{
click() {console. Log(' click')} 
drag() {Console. Log('drag')} 
drop() {console. Log('drop')}



The click function works fine but the two other do nothing. 

For now I can't create a jsfiddle. 

Do you have any idea of what I am doing wrong?

**Comment by pawelfus** [comment]
It's hard to say. Does it work with Highcharts? Is `dataGrouping` disabled? Without live demo we can only guess.
